# Generated by Django 4.2.11 on 2025-09-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamesshop', '0004_remove_order_shipping_address_order_shipping_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
